name: dueit nuxt deploy
on:
  pull_request:
    branches:
      - rama/DEPLOY/setup-docker
  push:
    branches:
      - rama/DEPLOY/setup-docker

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  nuxt-deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: build docker image
        if: ${{ github.ref == 'refs/heads/rama/DEPLOY/setup-docker' }}
        run: |
          docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:dev

      - name: push image
        run: |
          docker push $DOCKER_USER/$REPO_NAME:dev

      - name: deploy to vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSHKEY }}
          script: ${{ secrets.SERVER_SCRIPT }}

